[project]
org-name = "ballerina"
version = "0.7.0"

[dependencies]
"ballerina/runtime" = "0.5.0"
"ballerina/crypto" = "1.0.0"
"ballerina/http" = "1.0.0"
"ballerina/config" = "1.0.0"

[platform]
target = "java8"

    [[platform.libraries]]
    artifactId = "grpc"
    version = "0.7.0-SNAPSHOT"
    path = "../grpc-native/build/libs/grpc-native-0.7.0-SNAPSHOT.jar"
    groupId = "ballerina"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "grpc"
    version = "0.7.0-SNAPSHOT"
    path = "../grpc-test-utils/build/libs/grpc-test-utils-0.7.0-SNAPSHOT.jar"
    groupId = "org.ballerinalang"
    modules = ["grpc"]
    scope = "testOnly"

    [[platform.libraries]]
    artifactId = "http-native"
    version = "@http.native.version@"
    path = "./lib/http-native-@http.native.version@.jar"
    groupId = "org.ballerinalang"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "org.wso2.transport.http.netty"
    version = "6.3.11"
    path = "./lib/org.wso2.transport.http.netty-6.3.11.jar"
    groupId = "org.wso2.transport.http"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-common"
    version = "4.1.39.Final"
    path = "./lib/netty-common-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-buffer"
    version = "4.1.39.Final"
    path = "./lib/netty-buffer-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-transport"
    version = "4.1.39.Final"
    path = "./lib/netty-transport-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-resolver"
    version = "4.1.39.Final"
    path = "./lib/netty-resolver-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-handler"
    version = "4.1.39.Final"
    path = "./lib/netty-handler-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-codec-http"
    version = "4.1.39.Final"
    path = "./lib/netty-codec-http-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-codec"
    version = "4.1.39.Final"
    path = "./lib/netty-codec-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-handler-proxy"
    version = "4.1.39.Final"
    path = "./lib/netty-handler-proxy-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-codec-http2"
    version = "4.1.39.Final"
    path = "./lib/netty-codec-http2-4.1.39.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "commons-pool"
    version = "1.5.6.wso2v1"
    path = "./lib/commons-pool-1.5.6.wso2v1.jar"
    groupId = "commons-pool.wso2"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "snakeyaml"
    version = "1.16.0.wso2v1"
    path = "./lib/snakeyaml-1.16.0.wso2v1.jar"
    groupId = "org.wso2.orbit.org.yaml"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "bcprov-jdk15on"
    version = "1.61"
    path = "./lib/bcprov-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "bcpkix-jdk15on"
    version = "1.61"
    path = "./lib/bcpkix-jdk15on-1.61.jar"
    groupId = "org.bouncycastle"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "netty-tcnative-boringssl-static"
    version = "2.0.25.Final"
    path = "./lib/netty-tcnative-boringssl-static-2.0.25.Final.jar"
    groupId = "io.netty"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "protobuf-java"
    version = "3.9.1"
    path = "./lib/protobuf-java-3.9.1.jar"
    groupId = "com.google.protobuf"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "proto-google-common-protos"
    version = "1.17.0"
    path = "./lib/proto-google-common-protos-1.17.0.jar"
    groupId = "com.google.api.grpc"
    modules = ["grpc"]

    [[platform.libraries]]
    artifactId = "handlebars"
    version = "4.1.2"
    path = "./lib/handlebars-4.0.6.jar"
    groupId = "com.github.jknack"
    modules = ["grpc"]


[build-options]
observability-included=true
