[package]
org = "ballerina"
name = "grpc"
version = "@toml.version@"

[[platform.java11.dependency]]
path = "../grpc-native/build/libs/grpc-native-@project.version@.jar"
groupId = "ballerina"
artifactId = "grpc"
version = "@project.version@"

[[platform.java11.dependency]]
path = "../grpc-test-utils/build/libs/grpc-test-utils-@project.version@.jar"
groupId = "org.ballerinalang"
scope = "testOnly"
artifactId = "grpc"
version = "@project.version@"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-@ballerinalang.version@.jar"
groupId = "org.ballerinalang"
scope = "testOnly"
artifactId = "ballerina-cli"
version = "@ballerinalang.version@"

[[platform.java11.dependency]]
path = "./lib/antlr4-runtime-@antlr.version@.jar"
groupId = "org.wso2.orbit.org.antlr"
scope = "testOnly"
artifactId = "antlr4-runtime"
version = "@antlr.version@"

[[platform.java11.dependency]]
path = "./lib/http-native-@http.native.version@.jar"
groupId = "org.ballerinalang"
artifactId = "http-native"
version = "@http.native.version@"

[[platform.java11.dependency]]
path = "./lib/netty-common-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-common"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-buffer"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-transport-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-transport"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-resolver"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-handler-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-handler"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-codec-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-@netty.version@.jar"
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "@netty.version@"

[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"
groupId = "commons-pool.wso2"
artifactId = "commons-pool"
version = "1.5.6.wso2v1"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.61.jar"
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk15on"
version = "1.61"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.61.jar"
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk15on"
version = "1.61"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-@nettytcnative.version@.jar"
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "@nettytcnative.version@"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.9.1.jar"
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.9.1"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"
groupId = "com.google.api.grpc"
artifactId = "proto-google-common-protos"
version = "1.17.0"

[[platform.java11.dependency]]
path = "./lib/formatter-core-@ballerinalang.version@.jar"
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "@ballerinalang.version@"

[[platform.java11.dependency]]
path = "./lib/ballerina-parser-@ballerinalang.version@.jar"
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "@ballerinalang.version@"
