[package]
org = "ballerina"
name = "grpc"
version = "@toml.version@"
distribution = "2201.0.0"
authors = ["Ballerina"]
keywords = ["network", "grpc", "protobuf", "server-streaming", "client-streaming", "bidirectional-streaming"]
repository = "https://github.com/ballerina-platform/module-ballerina-grpc"
license = ["Apache-2.0"]
export = ["grpc", "grpc.types.duration", "grpc.types.struct", "grpc.types.timestamp", "grpc.types.wrappers", "grpc.types.any"]

[[platform.java11.dependency]]
path = "../native/build/libs/grpc-native-@project.version@.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-@project.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-@ballerinalang.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/antlr4-runtime-@antlr.version@.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/http-native-@http.native.version@.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-@protobuf.java.version@.jar"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-@proto.google.commons.version@.jar"

[[platform.java11.dependency]]
path = "./lib/formatter-core-@ballerinalang.version@.jar"

[[platform.java11.dependency]]
path = "./lib/ballerina-parser-@ballerinalang.version@.jar"
