[package]
org = "ballerina"
name = "grpc"
version = "1.3.0"
distribution = "2201.1.0"
authors = ["Ballerina"]
keywords = ["network", "grpc", "protobuf", "server-streaming", "client-streaming", "bidirectional-streaming"]
repository = "https://github.com/ballerina-platform/module-ballerina-grpc"
icon = "icon.png"
license = ["Apache-2.0"]
export = ["grpc", "grpc.types.duration", "grpc.types.struct", "grpc.types.timestamp", "grpc.types.wrappers", "grpc.types.any"]

[[platform.java11.dependency]]
path = "../native/build/libs/grpc-native-1.3.0-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.3.0-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2201.1.0-rc1.12.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/antlr4-runtime-4.5.1.wso2v1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/http-native-2.3.0-20220520-115500-3b6bb0d.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-classes-2.0.52.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.52.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.52.Final-windows-x86_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.52.Final-linux-aarch_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.52.Final-linux-x86_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.52.Final-osx-aarch_64.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.52.Final-osx-x86_64.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.20.1.jar"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java11.dependency]]
path = "./lib/formatter-core-2201.1.0-rc1.12.jar"

[[platform.java11.dependency]]
path = "./lib/ballerina-parser-2201.1.0-rc1.12.jar"
