[package]
org = "ballerina"
name = "grpc"
version = "1.10.9"
distribution = "2201.8.0"
authors = ["Ballerina"]
keywords = ["network", "grpc", "protobuf", "server-streaming", "client-streaming", "bidirectional-streaming"]
repository = "https://github.com/ballerina-platform/module-ballerina-grpc"
icon = "icon.png"
license = ["Apache-2.0"]
export = ["grpc", "grpc.types.duration", "grpc.types.struct", "grpc.types.timestamp", "grpc.types.wrappers", "grpc.types.any"]

[platform.java17]
graalvmCompatible = true

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "grpc-native"
version = "1.10.9"
path = "../native/build/libs/grpc-native-1.10.9-SNAPSHOT.jar"

[[platform.java17.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.10.9-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java17.dependency]]
path = "./lib/ballerina-cli-2201.8.0.jar"
scope = "testOnly"

[[platform.java17.dependency]]
path = "./lib/antlr4-runtime-4.5.1.wso2v1.jar"
scope = "testOnly"

[[platform.java17.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "http-native"
version = "2.10.14"
path = "./lib/http-native-2.10.14.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-common"
version = "4.1.108.Final"
path = "./lib/netty-common-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-buffer"
version = "4.1.108.Final"
path = "./lib/netty-buffer-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-transport"
version = "4.1.108.Final"
path = "./lib/netty-transport-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-resolver"
version = "4.1.108.Final"
path = "./lib/netty-resolver-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-handler"
version = "4.1.108.Final"
path = "./lib/netty-handler-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http"
version = "4.1.108.Final"
path = "./lib/netty-codec-http-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-codec"
version = "4.1.108.Final"
path = "./lib/netty-codec-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-handler-proxy"
version = "4.1.108.Final"
path = "./lib/netty-handler-proxy-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-codec-http2"
version = "4.1.108.Final"
path = "./lib/netty-codec-http2-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-transport-native-unix-common"
version = "4.1.108.Final"
path = "./lib/netty-transport-native-unix-common-4.1.108.Final.jar"

[[platform.java17.dependency]]
groupId = "commons.pool.wso2"
artifactId = "commons-pool"
version = "1.5.6.wso2v1"
path = "./lib/commons-pool-1.5.6.wso2v1.jar"

[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcprov-jdk18on"
version = "1.78"
path = "./lib/bcprov-jdk18on-1.78.jar"

[[platform.java17.dependency]]
groupId = "org.bouncycastle"
artifactId = "bcpkix-jdk18on"
version = "1.78"
path = "./lib/bcpkix-jdk18on-1.78.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-tcnative-classes"
version = "2.0.65.Final"
path = "./lib/netty-tcnative-classes-2.0.65.Final.jar"

[[platform.java17.dependency]]
groupId = "io.netty"
artifactId = "netty-tcnative-boringssl-static"
version = "2.0.65.Final"
path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final.jar"

[[platform.java17.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-windows-x86_64.jar"

[[platform.java17.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-linux-aarch_64.jar"

[[platform.java17.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-linux-x86_64.jar"

[[platform.java17.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-osx-aarch_64.jar"

[[platform.java17.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.65.Final-osx-x86_64.jar"

[[platform.java17.dependency]]
groupId = "com.google.protobuf"
artifactId = "protobuf-java"
version = "3.20.3"
path = "./lib/protobuf-java-3.20.3.jar"

[[platform.java17.dependency]]
groupId = "com.google.api.grpc"
artifactId = "proto-google-common-protos"
version = "1.17.0"
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java17.dependency]]
groupId = "org.ballerinalang"
artifactId = "formatter-core"
version = "2201.8.0"
path = "./lib/formatter-core-2201.8.0.jar"

[[platform.java17.dependency]]
groupId = "org.ballerinalang"
artifactId = "ballerina-parser"
version = "2201.8.0"
path = "./lib/ballerina-parser-2201.8.0.jar"
