[package]
org = "ballerina"
name = "grpc"
version = "1.0.1"
distribution = "slbeta3"
export = ["grpc", "grpc.types.duration", "grpc.types.struct", "grpc.types.timestamp", "grpc.types.wrappers"]

[[platform.java11.dependency]]
path = "../native/build/libs/grpc-native-1.0.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.0.1-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2.0.0-beta.4-20211021-141800-ca1c7cec.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/antlr4-runtime-4.5.1.wso2v1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/http-native-2.0.1-20211021-225400-ed7bd6d.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.68.Final.jar"

[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.43.Final.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.9.1.jar"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java11.dependency]]
path = "./lib/formatter-core-2.0.0-beta.4-20211021-141800-ca1c7cec.jar"

[[platform.java11.dependency]]
path = "./lib/ballerina-parser-2.0.0-beta.4-20211021-141800-ca1c7cec.jar"
