[package]
org = "ballerina"
name = "grpc"
version = "1.2.3"
distribution = "2201.0.1"
authors = ["Ballerina"]
keywords = ["network", "grpc", "protobuf", "server-streaming", "client-streaming", "bidirectional-streaming"]
repository = "https://github.com/ballerina-platform/module-ballerina-grpc"
icon = "icon.png"
license = ["Apache-2.0"]
export = ["grpc", "grpc.types.duration", "grpc.types.struct", "grpc.types.timestamp", "grpc.types.wrappers", "grpc.types.any"]

[[platform.java11.dependency]]
path = "../native/build/libs/grpc-native-1.2.3-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/grpc-test-utils-1.2.3-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/ballerina-cli-2201.0.1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/antlr4-runtime-4.5.1.wso2v1.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/http-native-2.2.1.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-handler-proxy-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-codec-http2-4.1.71.Final.jar"

[[platform.java11.dependency]]
path = "./lib/commons-pool-1.5.6.wso2v1.jar"

[[platform.java11.dependency]]
path = "./lib/bcprov-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/bcpkix-jdk15on-1.69.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-classes-2.0.46.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-tcnative-boringssl-static-2.0.46.Final.jar"

[[platform.java11.dependency]]
path = "./lib/protobuf-java-3.19.2.jar"

[[platform.java11.dependency]]
path = "./lib/proto-google-common-protos-1.17.0.jar"

[[platform.java11.dependency]]
path = "./lib/formatter-core-2201.0.1.jar"

[[platform.java11.dependency]]
path = "./lib/ballerina-parser-2201.0.1.jar"
