[[dependency]]
org = "ballerina"
name = "auth"
version = "@stdlib.auth.version@"

[[dependency]]
org = "ballerina"
name = "jwt"
version = "@stdlib.jwt.version@"

[[dependency]]
org = "ballerina"
name = "oauth2"
version = "@stdlib.oauth2.version@"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "@stdlib.crypto.version@"

[[dependency]]
org = "ballerina"
name = "regex"
version = "@stdlib.regex.version@"

[[dependency]]
org = "ballerina"
name = "time"
version = "@stdlib.time.version@"

[[dependency]]
org = "ballerina"
name = "os"
version = "@stdlib.os.version@"
